library(shiny)
library(shinythemes)
# theme options:"cerulean",  "sandstone", "simplex", "yeti", "cosmo", "lumen", "flatly"
shinyUI(fluidPage(
      theme = shinytheme("simplex"),
      titlePanel(strong("DIAMOND'S PRICE PREDICTION")),
      sidebarLayout(
            sidebarPanel(
                  helpText("This application predicts the price in $ of a diamond based on several attributes. Make your preferences and move the sliders."),
                  hr(),
                  sliderInput(inputId = "X",
                              label = "Length in millimeters:",
                              value = 2.2,
                              min = 0.5,
                              max = 10,
                              step = .1,
                              post = "mm"),
                  sliderInput(inputId = "Y",
                              label = "Width in millimeters:",
                              value = 5.2,
                              min = 0.5,
                              max = 10,
                              step = .1,
                              post = "mm"),
                  sliderInput(inputId = "Z",
                              label = "Depth in millimeters:",
                              value = 7.3,
                              min = 0.5,
                              max = 10,
                              step = .1,
                              post = "mm"),
                  hr(),
                  # helpText("Make a choice of the desired cut:"),
                  radioButtons(inputId = "RBcut",
                               label = "Desired cut: ",
                               choices = c("Fair" = "Fair", 
                                           "Good" = "Good",
                                           "Very Good" = "Very Good", 
                                           "Premium" = "Premium",
                                           "Ideal"="Ideal"),
                               selected = "Premium",
                               inline = TRUE),
                  hr(),
                  # helpText("Make a choice of the desired color:"),
                  selectInput(inputId = "Scolor",
                              label = "Desired color: ",
                              selected = "D",
                              choices = c("D (best)" = "D", 
                                          "E" = "E",
                                          "F" = "F", 
                                          "G" = "G",
                                          "H" = "H",
                                          "I" = "I",
                                          "J (worst)" = "J")),
                  hr(),
                  # helpText("Make a choice of the desired clarity: a measurement of how clear the diamond is"),
                  selectInput(inputId = "Sclar",
                              label = "Desired clarity: ",
                              selected = "IF",
                              choices = c("IF (best)" = "IF", 
                                          "VVS1" = "VVS1",
                                          "VVS2" = "VVS2",
                                          "VS2" = "VS2",
                                          "VS1" = "VS1",
                                          "SI1" = "SI1", 
                                          "SI2" = "SI2",
                                          "I1 (worst)" = "I1")),
                  hr(),
                  # helpText("Make a choice of the desired clarity: a measurement of how clear the diamond is"),
                  sliderInput(inputId = "carat",
                              label = "Choose the carat of the diamond:",
                              value = 1.2,
                              min = 0.1,
                              max = 4.5,
                              step = .01,
                              post = "ct.")
                  
                  
            ),
            
            mainPanel(
                  htmlOutput("detailedText"),
                  htmlOutput("prediction"),
                  hr(),
                  plotlyOutput("plot", width = "70%"),
                  verbatimTextOutput("outcome"),
                  hr(),
                  em("*This app is based on linear regression model. "),
                  br(),
                  em("The data set that it was derived from contains the prices and other attributes of almost 54,000 diamonds. "),
                  em("Name of the data set:", strong("diamonds")),
                  em(", R package:", strong("ggplot2"))
            )
      )
))